### ISSUE TITLE
new operator in php8 

### ISSUE THREAD

**Issue by smknstd** [chrisdicarlo/eloquent-human-timestamps#1]
Just read your [blog post](https://chrisdicarlo.ca/blog/eloquent-human-timestamps/) and I thought that php8 now lets you do this in your template :

`<div>{{ $last_logged_in?->diffForHumans() }}</div>`

So if I'm right, you might not need the package anymore (as soon as you'll run php8). Great library though but maybe you can mention that somewhere.

**Comment by chrisdicarlo** [comment]
Hi @smknstd , I don't see anything in the PHP docs for that and don't see anything on any of the "What's new in PHP 8" type sites?  Do you know where you saw the reference for that function?  Definitely would want to add a note about it in the README if it's true but I only see it in relation to Carbon.

Cheers,
Chris

**Comment by smknstd** [comment]
Not 100% sure about current status of this feature as there is no offcial manual pages for php8 yet, but as far as I understand this it will be available: https://wiki.php.net/rfc/nullsafe_operator

**Comment by chrisdicarlo** [comment]
Ah, didn't even think of the new nullsafe operator.  That's a fair point; I'll probably update the package to support PHP 8 (and use the nullsafe operator under the hood) that way you can either use the property syntax, i.e. _for_humans, or the method call, i.e. ->diffForHumans(), in the Blade templates.

**Comment by chrisdicarlo** [comment]
After reflecting, since the package works in both PHP 7 and PHP8 due to not utilizing any specific new language features and in the interests of not having to maintain 2 different branches depending on the PHP version, I'm going to close this issue.
